name: Sync goerli main

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Sync main with goerli-main
        run: |
          git fetch --unshallow
          git checkout goerli-main
          git pull
          git rebase main
          git push -f
