name: Sync goerli staging

on:
  push:
    branches:
      - github-actions

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Sync staging with goerli-staging
        run: |
          git fetch --unshallow
          git checkout goerli-staging
          git pull
          git rebase github-actions
          git push -f
